{
 "title": "All sites comparison",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Performance score",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "performance-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Best practice score",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "best-practices-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accessibility Score",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "accessibility-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SEO score",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "seo-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PWA score",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "pwa-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "First Contentful Paint",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "first-contentful-paint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "First Meaningful Paint",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "first-contentful-paint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speed Index",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "speed-index",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time to Interactive",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "interactive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}