{
 "title": "Versus",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Versus",
    "query": "SHOW TAG VALUES WITH KEY = \"url\""
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Performance score",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "performance-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$Versus$/" }
     ]
    }
   ]
  },
  {
   "title": "Best practice score",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "best-practices-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$Versus$/" }
     ]
    }
   ]
  },
  {
   "title": "Accessibility Score",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "accessibility-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$Versus$/" }
     ]
    }
   ]
  },
  {
   "title": "SEO score",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 7 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "seo-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$Versus$/" }
     ]
    }
   ]
  },
  {
   "title": "PWA score",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 7 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "pwa-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$Versus$/" }
     ]
    }
   ]
  },
  {
   "title": "Performance Metrics (Lower is better)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "content": "<style>\n.panel-title-text {\n  font-size: x-large;\n}\n</style>"
  },
  {
   "title": "Speed Index",
   "type": "graph",
   "description": "Speed Index shows how quickly the contents of a page are visibly populated.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "speed-index",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$Versus$/" }
     ]
    }
   ]
  },
  {
   "title": "First Contentful Paint",
   "type": "graph",
   "description": "First Contentful Paint marks the time at which the first text or image is painted.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "first-contentful-paint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$Versus$/" }
     ]
    }
   ]
  },
  {
   "title": "First CPU Idle",
   "type": "graph",
   "description": "First CPU Idle marks the first time at which the page's main thread is quiet enough to handle input.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "first-cpu-idle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$Versus$/" }
     ]
    }
   ]
  },
  {
   "title": "First Meaningful Paint",
   "type": "graph",
   "description": "First Meaningful Paint measures when the primary content of a page is visible.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "first-meaningful-paint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$Versus$/" }
     ]
    }
   ]
  },
  {
   "title": "Estimated Input Latency",
   "type": "graph",
   "description": "The score above is an estimate of how long your app takes to respond to user input, in milliseconds, during the busiest 5s window of page load. If your latency is higher than 50 ms, users may perceive your app as laggy.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "estimated-input-latency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$Versus$/" }
     ]
    }
   ]
  },
  {
   "title": "Time to Interactive",
   "type": "graph",
   "description": "Interactive marks the time at which the page is fully interactive.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "interactive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$Versus$/" }
     ]
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "DOM nodes Score",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 43 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "dom-size-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$Versus$/" }
     ]
    }
   ]
  },
  {
   "title": "DOM nodes",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 43 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "dom-size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$Versus$/" }
     ]
    }
   ]
  },
  {
   "title": "DOM max depth",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 43 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "dom-max-depth",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$Versus$/" }
     ]
    }
   ]
  },
  {
   "title": "DOM max child nodes",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 43 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "dom-max-child-elements",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$Versus$/" }
     ]
    }
   ]
  }
 ]
}