#!/bin/bash

export AWS_ACCESS_KEY_ID=ASIAS22R7VU7OAXPIRX7
export AWS_SECRET_ACCESS_KEY=HTfKdg0No/UTqTvPqIWd/HzPMwgW5GSh8Rw5DCiY
export AWS_SESSION_TOKEN=FQoGZXIvYXdzEEoaDLtrMXzdfna+dVW4dCKYAtj2KOEF5Lkynf+8JkfS3y8iXlkWB3eA0nGy5lkFJeV8s3Q3vmcps4ZUKJ0DRXjLfeYZMY48mMD0bIisqJMzBt6UmzZG06AbdedCyL5c6BHkO9xZmCyWmWtWck0+gAD2fppjMc6hqLpV9TdqxwOePLKe9KCqxLJ6WPzxOBadTS/0AqX7NlBdeUUEwZBH9FQbHCkJiFnkDtAuk4XfkTMJm1WD3PwZLCxZVT9jTPXxyt9Z0sEsScQyDOVYllcUH4R/NaR0GLPKJqUNUn/DwHpHo78W4sGQ0oay8EuFPVspuJmdHAF1OoEQvn+2LDjdUUlV+4bWmbh3kVHRPX/bjXhe/56CVRAXwsrAEMOsYp/g1mbLN/1X3DLSQmgoitHM4gU=
export AWS_SECURITY_TOKEN=FQoGZXIvYXdzEEoaDLtrMXzdfna+dVW4dCKYAtj2KOEF5Lkynf+8JkfS3y8iXlkWB3eA0nGy5lkFJeV8s3Q3vmcps4ZUKJ0DRXjLfeYZMY48mMD0bIisqJMzBt6UmzZG06AbdedCyL5c6BHkO9xZmCyWmWtWck0+gAD2fppjMc6hqLpV9TdqxwOePLKe9KCqxLJ6WPzxOBadTS/0AqX7NlBdeUUEwZBH9FQbHCkJiFnkDtAuk4XfkTMJm1WD3PwZLCxZVT9jTPXxyt9Z0sEsScQyDOVYllcUH4R/NaR0GLPKJqUNUn/DwHpHo78W4sGQ0oay8EuFPVspuJmdHAF1OoEQvn+2LDjdUUlV+4bWmbh3kVHRPX/bjXhe/56CVRAXwsrAEMOsYp/g1mbLN/1X3DLSQmgoitHM4gU=

export aws_access_key_id=ASIAS22R7VU7OAXPIRX7
export aws_secret_access_key=HTfKdg0No/UTqTvPqIWd/HzPMwgW5GSh8Rw5DCiY
export aws_session_token=FQoGZXIvYXdzEEoaDLtrMXzdfna+dVW4dCKYAtj2KOEF5Lkynf+8JkfS3y8iXlkWB3eA0nGy5lkFJeV8s3Q3vmcps4ZUKJ0DRXjLfeYZMY48mMD0bIisqJMzBt6UmzZG06AbdedCyL5c6BHkO9xZmCyWmWtWck0+gAD2fppjMc6hqLpV9TdqxwOePLKe9KCqxLJ6WPzxOBadTS/0AqX7NlBdeUUEwZBH9FQbHCkJiFnkDtAuk4XfkTMJm1WD3PwZLCxZVT9jTPXxyt9Z0sEsScQyDOVYllcUH4R/NaR0GLPKJqUNUn/DwHpHo78W4sGQ0oay8EuFPVspuJmdHAF1OoEQvn+2LDjdUUlV+4bWmbh3kVHRPX/bjXhe/56CVRAXwsrAEMOsYp/g1mbLN/1X3DLSQmgoitHM4gU=
export aws_security_token=FQoGZXIvYXdzEEoaDLtrMXzdfna+dVW4dCKYAtj2KOEF5Lkynf+8JkfS3y8iXlkWB3eA0nGy5lkFJeV8s3Q3vmcps4ZUKJ0DRXjLfeYZMY48mMD0bIisqJMzBt6UmzZG06AbdedCyL5c6BHkO9xZmCyWmWtWck0+gAD2fppjMc6hqLpV9TdqxwOePLKe9KCqxLJ6WPzxOBadTS/0AqX7NlBdeUUEwZBH9FQbHCkJiFnkDtAuk4XfkTMJm1WD3PwZLCxZVT9jTPXxyt9Z0sEsScQyDOVYllcUH4R/NaR0GLPKJqUNUn/DwHpHo78W4sGQ0oay8EuFPVspuJmdHAF1OoEQvn+2LDjdUUlV+4bWmbh3kVHRPX/bjXhe/56CVRAXwsrAEMOsYp/g1mbLN/1X3DLSQmgoitHM4gU=
# create cluster: aws ecs create-cluster --cluster-name webperf_cluster --region=us-east-1

ecs-cli configure profile \
  --profile-name hbc-common \
  --access-key $AWS_ACCESS_KEY_ID \
  --secret-key $AWS_SECRET_ACCESS_KEY

ecs-cli configure --cluster webperf_cluster --default-launch-type FARGATE --region us-east-1 --config-name webperf_config


  ecs-cli compose --project-name webperf-dashboard --file docker-compose.yml --ecs-params ecs-params.yml create

  ecs-cli compose --cluster webperf_cluster --file docker-compose.yml --ecs-params ecs-params.yml start --launch-type FARGATE
