{
 "title": "Single Web Page Audit",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "url",
    "query": "SHOW TAG VALUES WITH KEY = \"url\""
   },
   {
    "name": "LIGHTHOUSE_HOST",
    "query": "inspector-lighthouse.observe.tools.common.awshbc.io"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Performance",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "performance-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "Best Practices",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "best-practices-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "Accessibility",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "accessibility-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "SEO",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "seo-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
   "content": "<style>\n.scorescale {\n  font-size: 20px;\n  display: flex;\n  justify-content: flex-end;\n}\n.scorescale > * {\n  margin-left: 10px;\n}\n.pass::before {\n  background-color: #299c46;\n  content: '';\n  width: 30px;\n  height: 15px;\n  border-radius: 4px;\n  display: inline-block;\n  margin: 0 5px;\n}\n\n.average::before {\n  background-color: rgba(237, 129, 40, 0.89);\n  content: '';\n  width: 30px;\n  height: 15px;\n  border-radius: 4px;\n  display: inline-block;\n  margin: 0 5px;\n}\n.fail::before {\n  background-color: #d44a3a;\n  content: '';\n  width: 30px;\n  height: 15px;\n  border-radius: 4px;\n  display: inline-block;\n  margin: 0 5px;\n}\n</style>\n<div class=\"scorescale\">\n    <span class=\"\">Score scale:</span>\n    <span class=\"pass\">90-100</span>\n    <span class=\"average\">50-89</span>\n    <span class=\"fail\">0-49</span>\n</div>"
  },
  {
   "title": "Performance Metrics (Lower is better)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "First Contentful Paint",
   "type": "graph",
   "description": "First Contentful Paint marks the time at which the first text or image is painted.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "First Contentful Paint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "first-contentful-paint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "First Meaningful Paint",
   "type": "graph",
   "description": "First Meaningful Paint measures when the primary content of a page is visible.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "First Meaningful Paint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "first-meaningful-paint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "Speed Index",
   "type": "graph",
   "description": "Speed Index shows how quickly the contents of a page are visibly populated.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Speed Index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "speed-index",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "Time to Interactive",
   "type": "graph",
   "description": "Interactive marks the time at which the page is fully interactive.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Time to Interactive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interactive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "First CPU Idle",
   "type": "graph",
   "description": "First CPU Idle marks the first time at which the page's main thread is quiet enough to handle input.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "First CPU Idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "first-cpu-idle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "Estimated Input Latency",
   "type": "graph",
   "description": "The score above is an estimate of how long your app takes to respond to user input, in milliseconds, during the busiest 5s window of page load. If your latency is higher than 50 ms, users may perceive your app as laggy.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Estimated Input Latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "estimated-input-latency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  { "title": "Others", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "DOM nodes",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dom-size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "DOM max nodes depth",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dom-max-depth",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "DOM Max child nodes",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dom-max-child-elements",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "DOM nodes count score",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 39 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dom-size-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Bytes Downloaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "total-byte-weight",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "Downloaded Bytes SCORE",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 46 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total-byte-weight-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network-requests",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "content": "<style>\n.panel-title-text {\n  font-size: x-large;\n}\n</style>"
  },
  { "title": "Last Report", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "type": "text",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 55 },
   "content": "<style>\n iframe {\n  width: 100%;\n  height: 100%;\n  text-rendering: optimizeLegibility;\n\n }\n #site {\n   visibility: hidden;\n }\n</style>\n<div id=\"site\">$url</div>\n<iframe></iframe>\n<script>\n  iframe = document.querySelector('iframe');\n  site = document.querySelector('#site').innerHTML.replace(/(^\\w+:|^)\\/\\//, '');\n  iframe.src = `http://$LIGHTHOUSE_HOST/reports/${site}/LATEST.html#performance`;\n</script>"
  }
 ]
}