export function america(str: any): any;
export const bgBlack: any;
export const bgBlue: any;
export const bgCyan: any;
export const bgGreen: any;
export const bgMagenta: any;
export const bgRed: any;
export const bgWhite: any;
export const bgYellow: any;
export const black: any;
export const blackBG: any;
export const blue: any;
export const blueBG: any;
export const bold: any;
export const cyan: any;
export const cyanBG: any;
export const dim: any;
export function disable(): void;
export function enable(): void;
export const enabled: boolean;
export const gray: any;
export const green: any;
export const greenBG: any;
export const grey: any;
export const hidden: any;
export const inverse: any;
export const italic: any;
export const magenta: any;
export const magentaBG: any;
export namespace maps {
  function america(letter: any, i: any, exploded: any): any;
  function rainbow(letter: any, i: any, exploded: any): any;
  function random(letter: any, i: any, exploded: any): any;
  function zebra(letter: any, i: any, exploded: any): any;
}
export function rainbow(str: any): any;
export function random(str: any): any;
export const red: any;
export const redBG: any;
export const reset: any;
export function setTheme(theme: any): void;
export const strikethrough: any;
export function strip(str: any): any;
export function stripColors(str: any): any;
export const styles: {
  bgBlack: any[];
  bgBlue: any[];
  bgCyan: any[];
  bgGreen: any[];
  bgMagenta: any[];
  bgRed: any[];
  bgWhite: any[];
  bgYellow: any[];
  black: any[];
  blackBG: any[];
  blue: any[];
  blueBG: any[];
  bold: any[];
  cyan: any[];
  cyanBG: any[];
  dim: any[];
  gray: any[];
  green: any[];
  greenBG: any[];
  grey: any[];
  hidden: any[];
  inverse: any[];
  italic: any[];
  magenta: any[];
  magentaBG: any[];
  red: any[];
  redBG: any[];
  reset: any[];
  strikethrough: any[];
  underline: any[];
  white: any[];
  whiteBG: any[];
  yellow: any[];
  yellowBG: any[];
};
export function stylize(str: any, style: any): any;
export function supportsColor(stream: any): any;
export const themes: {};
export function trap(text: any, options: any): any;
export const underline: any;
export const white: any;
export const whiteBG: any;
export const yellow: any;
export const yellowBG: any;
export function zalgo(text: any, options: any): any;
export function zebra(str: any): any;
